### ISSUE TITLE
Error, wenn "Elternseite" nicht veröffentlicht

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-changelanguage#96]
terminal42/contao-changelanguage 	3.1.0

ich habe im Seitenbaum bei EN (Fallback ist DE) eine übergeordnete Seite deaktiviert - wird eine untergeordnete Seite (aktiv) aufgerufen, kommt ein Fatal Error:

```
[16-Dec-2016 11:59:55 Europe/Berlin] PHP Fatal error: Uncaught exception 'RuntimeException' with message 'Parent page for page ID "911" not found' thrown in /home/xyz/contao/composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/PageFinder.php on line 210
#0 /home/xyz/contao/composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/Navigation/NavigationFactory.php(70): Terminal42\ChangeLanguage\PageFinder->findAssociatedParentForLanguage(Object(Contao\PageModel), 'pl')
#1 /home/xyz/contao/composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(71): Terminal42\ChangeLanguage\Navigation\NavigationFactory->findNavigationItems(Object(Contao\PageModel))
#2 /home/xyz/contao/system/modules/core/modules/Module.php(287): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->compile()
#3 /home/xyz/contao/composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#4 /home/xyz/contao/composer/vendor/terminal42/contao-changelanguage/library/Terminal42/ChangeLanguage/FrontendModule/ChangeLanguageModule.php(51): Haste\Frontend\AbstractFrontendModule->generate()
#5 /home/xyz/contao/system/modules/core/library/Contao/Controller.php(321): Terminal42\ChangeLanguage\FrontendModule\ChangeLanguageModule->generate()
#6 /home/xyz/contao/system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('40')
#7 /home/xyz/contao/system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('<!doctype html>...', false)
#8 /home/xyz/contao/system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('<!doctype html>...', false)
#9 /home/xyz/contao/system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#10 /home/xyz/contao/system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 /home/xyz/contao/index.php(20): Contao\FrontendIndex->run()
#12 {main}
```

**Comment by aschempp** [comment]
Fixed in 7c6e4fbe467f983d069a60e8a7249685f1a34877
